version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=javy
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=pearl_db
    ports:
      - "5432:5432"
  redis:
    image: redis:5.0.7
    #command: redis-server /etc/conf/redis.conf
    volumes:
      - db_redis:/data
        #- ./conf/redis.conf:/etc/conf/redis.conf
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123123
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3001 -b '0.0.0.0'"
    #privileged: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - db
    environment:
      DB_USERNAME: javy
      DB_DATABASE: pearl_db
      DB_PORT: 5432
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      EDITOR: vi
      TZ: Asia/Beijing
      LANG: zh-CN.UTF-8
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - redis
      - db
      - web
    environment:
      DB_USERNAME: javy
      DB_DATABASE: pearl_db
      DB_PORT: 5432
      DB_HOST: db
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      TZ: Asia/Beijing
      LANG: zh-CN.UTF-8
    entrypoint: ["sh","./sidekiq-entrypoint.sh"]
volumes:
  db_data:
  db_redis:
  gem_cache:
  node_modules:


